name: validate
on:
  push:
    branches:
      - master
  pull_request_target: {}

jobs:
  main:
    strategy:
      matrix:
        node: [12, 14]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
