name: validate
on:
  push:
    branches:
      - master
  pull_request_target: {}

jobs:
  main:
    strategy:
      matrix:
        node: [12, 14]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Download dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ▶️ Run test
        run: npm run test
